version: 2.1

orbs:
  bud:
    executors:
      node-10:
        docker:
          - image: 'circleci/node:10-stretch'
    jobs:
      build-node:
        executor: node-10
        steps:
          - run: yarn versions
          - checkout
          - restore_cache:
              keys:
                - node-v1-{{ checksum "yarn.lock" }}
                - node-v1-
          - run: yarn install --frozen-lockfile
          - run: yarn run lint
          - run: yarn run build
          - run: yarn run docs
          - run: node ./bin/bud --default
          - save_cache:
              key: node-v1-{{ checksum "yarn.lock" }}
              paths:
                - node_modules

workflows:
  build:
    jobs:
      - bud/build-node
