/**
 * bud generate plugin
 */

// prettier-ignore
module.exports = {
  name: 'plugin',
  description: 'Generate a new plugin',
  tasks: [
    {
      action: 'compile',
      src: 'README.md.hbs',
      dest: 'README.md',
      parser: 'markdown',
    },
    {
      action: 'compile',
      src: 'LICENSE.md.hbs',
      dest: 'LICENSE.md',
      parser: 'markdown',
    },
    {
      action: 'compile',
      src: 'plugin.php.hbs',
      dest: 'plugin.php',
    },
    {
      action: 'compile',
      src: 'composer.json.hbs',
      dest: 'composer.json',
      parser: 'json',
    },
    {
      action: 'compile',
      src: 'babel.config.js',
      dest: 'babel.config.js',
      parser: 'babel',
    },
    {
      action: 'compile',
      src: '.editorconfig',
      dest: '.editorconfig',
    },
    {
      action: 'compile',
      src: '.eslintrc.js',
      dest: '.eslintrc.js',
      parser: 'babel',
    },
    {
      action: 'compile',
      src: '.eslintignore',
      dest: '.eslintignore',
    },
    {
      action: 'compile',
      src: '.gitignore',
      dest: '.gitignore',
    },
    {
      action: 'compile',
      src: 'postcss.config.js',
      dest: 'postcss.config.js',
      parser: 'babel',
    },
    {
      action: 'compile',
      src: 'prettier.config.js',
      dest: 'prettier.config.js',
      parser: 'babel',
    },
    {
      action: 'compile',
      src: '.prettierignore',
      dest: '.prettierignore',
    },
    {
      action: 'compile',
      src: 'stylelint.config.js',
      dest: 'stylelint.config.js',
      parser: 'babel',
    },
    {
      action: 'compile',
      src: 'webpack.config.js.hbs',
      dest: 'webpack.config.js',
      parser: 'babel',
    },
    {
      action: 'compile',
      src: 'uninstall.php.hbs',
      dest: 'uninstall.php',
    },
    {
      action: 'compile',
      src: 'app/bootstrap.php.hbs',
      dest: 'app/bootstrap.php',
    },
    {
      action: 'compile',
      src: 'app/Plugin/Activate.php.hbs',
      dest: 'app/Plugin/Activate.php',
    },
    {
      action: 'compile',
      src: 'app/Plugin/Deactivate.php.hbs',
      dest: 'app/Plugin/Deactivate.php',
    },
    {
      action: 'compile',
      src: 'app/Plugin/Registration.php.hbs',
      dest: 'app/Plugin/Registration.php',
    },
    {
      action: 'compile',
      src: 'app/Asset/Asset.php.hbs',
      dest: 'app/Asset/Asset.php',
    },
    {
      action: 'compile',
      src: 'app/Asset/Base/AbstractAsset.php.hbs',
      dest: 'app/Asset/Base/AbstractAsset.php',
    },
    {
      action: 'compile',
      src: 'app/Asset/Contract/AssetInterface.php.hbs',
      dest: 'app/Asset/Contract/AssetInterface.php',
    },
    {
      action: 'compile',
      src: 'app/Asset/Manifest.php.hbs',
      dest: 'app/Asset/Manifest.php',
    },
    {
      action: 'compile',
      src: 'app/Asset/Base/AbstractManifest.php.hbs',
      dest: 'app/Asset/Base/AbstractManifest.php',
    },
    {
      action: 'compile',
      src: 'app/Asset/Contract/ManifestInterface.php.hbs',
      dest: 'app/Asset/Contract/ManifestInterface.php',
    },
    {
      action: 'compile',
      src: 'app/Block/Block.php.hbs',
      dest: 'app/Block/Block.php',
    },
    {
      action: 'compile',
      src: 'app/Block/Base/AbstractBlock.php.hbs',
      dest: 'app/Block/Base/AbstractBlock.php',
    },
    {
      action: 'compile',
      src: 'app/Block/Contract/BlockInterface.php.hbs',
      dest: 'app/Block/Contract/BlockInterface.php',
    },
    {
      action: 'compile',
      src: 'app/Block/BlockRepository.php.hbs',
      dest: 'app/Block/BlockRepository.php',
    },
    {
      action: 'compile',
      src: 'app/Block/Contract/BlockRepositoryInterface.php.hbs',
      dest: 'app/Block/Contract/BlockRepositoryInterface.php',
    },
    {
      action: 'scaffold',
      paths: ['app/Block/Partials'],
    },
    {
      action: 'scaffold',
      paths: [
        'src',
        'src/blocks',
        'src/components',
        'src/extensions',
      ],
    },
    {
      action: 'addDependencies',
      repo: 'packagist',
      dev: false,
      pkgs: [
        'php-di/php-di',
        'tightenco/collect',
        'roots/support',
      ],
    },
    {
      action: 'addDependencies',
      repo: 'npm',
      dev: true,
      pkgs: [
        '@babel/cli',
        '@babel/core',
        '@babel/preset-env',
        '@babel/preset-react',
        '@wordpress/browserslist-config',
        '@wordpress/dependency-extraction-webpack-plugin',
        'autoprefixer',
        'assets-webpack-plugin',
        'babel-eslint',
        'babel-loader',
        'clean-webpack-plugin',
        'cross-env',
        'css-loader',
        'cssnano',
        'eslint',
        'eslint-loader',
        'eslint-plugin-import',
        'eslint-plugin-jsx-a11y',
        'eslint-plugin-react',
        'eslint-plugin-react-hooks',
        'extract-loader',
        'file-loader',
        'friendly-errors-webpack-plugin',
        'mini-css-extract-plugin',
        'npm-run-all',
        'postcss-import',
        'postcss-loader',
        'postcss-preset-env',
        'prettier',
        'prop-types',
        'react',
        'react-dom',
        'style-loader',
        'stylelint',
        'stylelint-config-standard',
        'uglifyjs-webpack-plugin',
        'url-loader',
        'webpack',
        'webpack-cli',
        'webpack-dev-server',
        'webpack-manifest-plugin',
        'webpackbar',
        'write-file-webpack-plugin',
      ],
    },
    {
      action: 'json',
      file: 'package.json',
      merge: pkg => ({
        ...pkg,
        browserslist: ['extends @wordpress/browserslist-config'],
        scripts: {
          ...pkg.scripts,
          dev: 'cross-env NODE_ENV=hmr webpack-dev-server --colors --watch --https --config webpack.config.js',
          build: 'cross-env NODE_ENV=development webpack --progress --colors --inline -p --config webpack.config.js',
          'build:production': 'cross-env NODE_ENV=production webpack --progress --colors --inline -p --config webpack.config.js',
          lint: 'run-s -c lint:*',
          'lint:css': 'stylelint ./src/**/*.css',
          'lint:js': 'eslint ./src/**/*.js',
          format: 'prettier --write .',
          translate: 'run-s -c translate:*',
          'translate:pot':
          'wp i18n make-pot . ./src/languages/plugin.pot --ignore-domain --include="./src"',
          'translate:js':
          'wp i18n make-json ./src/languages --no-purge --pretty-print',
        },
      }),
    },
  ],
}
